name: krakensistema
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.17.4
  firebase_core: ^2.30.0
  cloud_firestore: ^4.13.1
  intl: ^0.18.1
  google_fonts: ^5.1.0
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/telefono.png
    - assets/images/logokraken.png
